"""
Django settings for tldp project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os

from pathlib import Path

env = environ.Env()
env.read_env(os.path.join(os.path.dirname(__file__), "../.env"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)


ALLOWED_HOSTS = ["new.tldp.org"]

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "addressing_style": "path",
            "bucket_name": "ldp",
            "custom_domain": "cdn.tldp.org",
            "endpoint_url": "https://cdn.tldp.org",
            "signature_version": "s3v4",
            "querystring_auth": True,
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "location": "static",
            "addressing_style": "path",
            "bucket_name": "web",
            "custom_domain": "cdn.tldp.org/web",
            "endpoint_url": "https://cdn.tldp.org",
            "querystring_auth": False,
            "default_acl": "public-read",
        },
    },
}

AWS_S3_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_S3_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", default="https://cdn.tldp.org")
AWS_S3_BUCKET_NAME = "ldp"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

ROOT_URLCONF = "tldp.urls"

# MeiliSearch
MEILISEARCH = {
    "HOST": env("MEILI_URL", default="localhost"),
    "MASTER_KEY": env("MEILI_PASS", default=""),
    "HTTPS": False,
    "PORT": env.int("MEILI_PORT", default=7700),
}
